<h1>Knockout</h1>
<div data-bind="scope: 'knockoutExampleScope'">
    <p>First name: <strong data-bind="text: firstName"></strong></p>
    <p>Last name: <strong data-bind="text: lastName"></strong></p>

    <p>First name: <input data-bind="value: firstName" /></p>
    <p>Last name: <input data-bind="value: lastName" /></p>

    <p>Full name: <strong data-bind="text: firstName() + ' ' + lastName()"></strong></p>

    <button data-bind="click: capitalizeLastName">Go caps</button>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "knockoutExampleScope": {
                    "component": "Niall_KnockoutTutorial/js/view/example"
                }
            }
        }
    }
}
</script>