<?php
/* @var \Niall\KnockoutTutorial\ViewModel\Block1 $viewModel */
$viewModel = $block->getData('viewModel') ;
?>

<div data-bind="scope: 'knockoutExample1Scope'", style="border: 1px solid red">
    <h1>Knockout</h1>
    <p>First name: <strong data-bind="text: firstName"></strong></p>
    <p>Last name: <strong data-bind="text: lastName"></strong></p>

    <p>First name: <input data-bind="value: firstName" /></p>
    <p>Last name: <input data-bind="value: lastName" /></p>

    <p>Full name: <strong data-bind="text: firstName() + ' ' + lastName()"></strong></p>

    <button data-bind="click: capitalizeLastName">Go caps</button>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "knockoutExample1Scope": {
                    "component": "Niall_KnockoutTutorial/js/view/tutorial1",
                    "firstName": "<?= $viewModel->getFirstName() ?>",
                    "lastName": "<?= $viewModel->getLastName() ?>"
                }
            }
        }
    }
}
</script>