<div data-bind="scope: 'knockoutExample2Scope'", style="border: 1px solid green">
    <h2>Your seat reservations</h2>
    <table>
        <thead><tr>
            <th>Passenger name</th><th>Meal</th><th>Surcharge</th><th></th>
        </tr></thead>
            <tbody data-bind="foreach: seats">
            <tr>
                <td data-bind="text: name"></td>
                <td data-bind="text: meal().mealName"></td>
                <td data-bind="text: meal().price"></td>
            </tr>
        </tbody>
        <tbody></tbody>
    </table>
    <button data-bind="click: addSeat">Reserve another seat</button>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "knockoutExample2Scope": {
                    "component": "Niall_KnockoutTutorial/js/view/tutorial2"
                }
            }
        }
    }
}
</script>